definitions:
  poeticmetric.AuthenticationOrganization:
    properties:
      name:
        type: string
    type: object
  poeticmetric.AuthenticationUser:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      isEmailVerified:
        type: boolean
      isOrganizationOwner:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
  poeticmetric.AuthenticationUserAccessToken:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      token:
        type: string
    type: object
  poeticmetric.BootstrapServiceRunParams:
    properties:
      createDemoSite:
        type: boolean
      organizationName:
        type: string
      userEmail:
        type: string
      userName:
        type: string
      userPassword:
        type: string
      userPassword2:
        type: string
    type: object
  poeticmetric.CreateOrganizationSiteParams:
    properties:
      domain:
        type: string
      googleSearchConsoleSiteURL:
        type: string
      isPublic:
        type: boolean
      name:
        type: string
      safeQueryParameters:
        items:
          type: string
        type: array
    type: object
  poeticmetric.InviteOrganizationUserParams:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  poeticmetric.OrganizationDeletionParams:
    properties:
      detail:
        type: string
      reason:
        type: string
    type: object
  poeticmetric.OrganizationDeletionReason:
    properties:
      detailTitle:
        type: string
      order:
        type: integer
      reason:
        type: string
    type: object
  poeticmetric.OrganizationSite:
    properties:
      createdAt:
        type: string
      domain:
        type: string
      googleSearchConsoleSiteURL:
        type: string
      hasEvents:
        type: boolean
      id:
        type: integer
      isPublic:
        type: boolean
      name:
        type: string
      safeQueryParameters:
        items:
          type: string
        type: array
      updatedAt:
        type: string
    type: object
  poeticmetric.OrganizationUser:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      isEmailVerified:
        type: boolean
      isOrganizationOwner:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
  poeticmetric.ResetUserPasswordParams:
    properties:
      passwordResetToken:
        type: string
      userPassword:
        type: string
      userPassword2:
        type: string
    type: object
  poeticmetric.SendUserPasswordRecoveryEmailParams:
    properties:
      email:
        type: string
    type: object
  poeticmetric.UpdateOrganizationSiteParams:
    properties:
      domain:
        type: string
      googleSearchConsoleSiteURL:
        type: string
      isPublic:
        type: boolean
      name:
        type: string
      safeQueryParameters:
        items:
          type: string
        type: array
    type: object
  poeticmetric.UpdateOrganizationUserParams:
    properties:
      name:
        type: string
    type: object
  responder.DetailResponse:
    properties:
      detail:
        description: Human-readable detail of the response.
        type: string
    type: object
info:
  contact: {}
  description: This is a REST API for PoeticMetric.
  termsOfService: https://poeticmetric.com/terms-of-service
  title: PoeticMetric REST API
  version: "1.0"
paths:
  /authentication/change-user-password:
    post:
      description: Change currently authenticated user's password.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responder.DetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - BasicAuthentication: []
      summary: Change password
      tags:
      - authentication
  /authentication/organization:
    delete:
      description: Delete organization and all associated data irreversibly.
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.OrganizationDeletionParams'
      responses:
        "204":
          description: No Content
      security:
      - BasicAuthentication: []
      summary: Delete organization
      tags:
      - authentication
    get:
      description: Read currently authenticated user's organization.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/poeticmetric.AuthenticationOrganization'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - UserAccessTokenAuthentication: []
      summary: Read organization
      tags:
      - authentication
    patch:
      description: Update currently authenticated user's organization.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/poeticmetric.AuthenticationOrganization'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - UserAccessTokenAuthentication: []
      summary: Update organization
      tags:
      - authentication
  /authentication/organization-deletion-reasons:
    get:
      description: List possible organization deletion reasons.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationDeletionReason'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: List organization deletion reasons
      tags:
      - authentication
  /authentication/reset-user-password:
    post:
      description: Reset user's password also deleting all existing user access tokens
        for that user.
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.ResetUserPasswordParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responder.DetailResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/poeticmetric.ResetUserPasswordParams'
      summary: Reset user's password
      tags:
      - authentication
  /authentication/send-user-password-recovery-email:
    post:
      description: Send a password recovery e-mail to the user.
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.SendUserPasswordRecoveryEmailParams'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      summary: Send user password recovery e-mail
      tags:
      - authentication
  /authentication/user:
    get:
      description: Read currently authenticated user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/poeticmetric.AuthenticationUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - UserAccessTokenAuthentication: []
      summary: Read user
      tags:
      - authentication
    patch:
      description: Update currently authenticated user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/poeticmetric.AuthenticationUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - UserAccessTokenAuthentication: []
      summary: Update user
      tags:
      - authentication
  /authentication/user-access-tokens:
    delete:
      description: Delete user access token currently in use.
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - UserAccessTokenAuthentication: []
      summary: Delete user access token
      tags:
      - authentication
    post:
      description: Create a user access token by authenticating with the e-mail address
        and password.
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/poeticmetric.AuthenticationUserAccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - BasicAuthentication: []
      summary: Create user access token
      tags:
      - authentication
  /bootstrap:
    get:
      description: check if the bootstrap process is already done.
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      summary: Check bootstrap status
      tags:
      - boostrap
    post:
      description: check if the bootstrap process is already done.
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.BootstrapServiceRunParams'
      responses:
        "201":
          description: Created
      summary: Run bootstrap
      tags:
      - boostrap
  /sites:
    get:
      description: List sites.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationSite'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: List sites
      tags:
      - sites
    post:
      description: Create site.
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.CreateOrganizationSiteParams'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/poeticmetric.OrganizationSite'
      security:
      - UserAccessTokenAuthentication: []
      summary: Create site
      tags:
      - sites
  /sites/{siteID}:
    delete:
      description: Delete an organization site.
      parameters:
      - description: Site ID
        in: path
        name: siteID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      security:
      - UserAccessTokenAuthentication: []
      summary: Delete site
      tags:
      - sites
    get:
      description: Read an organization site.
      parameters:
      - description: Site ID
        in: path
        name: siteID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationSite'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: Read site
      tags:
      - sites
    patch:
      description: Update organization site.
      parameters:
      - description: Site ID
        in: path
        name: siteID
        required: true
        type: integer
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.UpdateOrganizationSiteParams'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationSite'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: Update site
      tags:
      - sites
  /users:
    get:
      description: List users.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationUser'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: List users
      tags:
      - users
    post:
      description: Invite a new user to organization.
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.InviteOrganizationUserParams'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationUser'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: Invite user
      tags:
      - users
  /users/{userID}:
    delete:
      description: Delete a user from the organization.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      security:
      - UserAccessTokenAuthentication: []
      summary: Delete user
      tags:
      - users
    get:
      description: Read a user from the organization.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationUser'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: Read user
      tags:
      - users
    patch:
      description: Update organization user.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.UpdateOrganizationUserParams'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/poeticmetric.OrganizationUser'
            type: array
      security:
      - UserAccessTokenAuthentication: []
      summary: Update user
      tags:
      - users
securityDefinitions:
  BasicAuthentication:
    type: basic
  UserAccessTokenAuthentication:
    description: User access token authentication.
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
