definitions:
  poeticmetric.AuthenticationServiceUserAccessToken:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      token:
        type: string
    type: object
  poeticmetric.BootstrapServiceRunParams:
    properties:
      createDemoSite:
        type: boolean
      organizationName:
        type: string
      userEmail:
        type: string
      userName:
        type: string
      userPassword:
        type: string
      userPassword2:
        type: string
    type: object
  responder.DetailResponse:
    properties:
      detail:
        description: Human-readable detail of the response.
        type: string
    type: object
info:
  contact: {}
  description: This is a REST API for PoeticMetric.
  termsOfService: https://poeticmetric.com/terms-of-service
  title: PoeticMetric REST API
  version: "1.0"
paths:
  /authentication/user-access-tokens:
    post:
      description: create a user access token by authenticating with the e-mail address
        and password
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/poeticmetric.AuthenticationServiceUserAccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      security:
      - BasicAuthentication: []
      summary: Create user access token
      tags:
      - authentication
  /bootstrap:
    get:
      description: check if the bootstrap process is already done
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responder.DetailResponse'
      summary: Check bootstrap status
      tags:
      - boostrap
    post:
      description: check if the bootstrap process is already done
      parameters:
      - description: Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/poeticmetric.BootstrapServiceRunParams'
      responses:
        "201":
          description: Created
      summary: Run bootstrap
      tags:
      - boostrap
securityDefinitions:
  BasicAuthentication:
    type: basic
swagger: "2.0"
