apiVersion: v2
appVersion: "1.0.0"
description: Free as in freedom, open source, privacy-first, regulation-compliant, and blazingly fast Google Analytics alternative.
name: poeticmetric
type: application
version: 1.0.0
