clickhouse:
  image:
    pullPolicy: IfNotPresent
    repository: clickhouse/clickhouse-server
    tag: 25.2
  password: ""
  persistence:
    enabled: true
    size: 10Gi
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  user: poeticmetric
ghcrAuth: ""
mailpit:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: axllent/mailpit
    tag: latest
  ingress:
    annotations: {} # @schema additionalProperties: true
    host: ""
pgbouncer:
  config: {} # @schema additionalProperties: true
  image:
    pullPolicy: IfNotPresent
    repository: bitnami/pgbouncer
    tag: "1"
  replicas: 1
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
postgres:
  image:
    pullPolicy: IfNotPresent
    repository: postgres
    tag: 17-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  user: poeticmetric
poeticmetric:
  backend:
    image:
      pullPolicy: Always
      repository: ghcr.io/th0th/poeticmetric/backend
      tag: latest
  development:
    databaseDebug: false
    debug: false
    enabled: false
    hostBasePath: ""
  frontend:
    image:
      pullPolicy: Always
      repository: ghcr.io/th0th/poeticmetric/frontend
      tag: latest
    ingress:
      annotations: {} # @schema additionalProperties: true
    replicas: 1
    resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
    tagsEnvironment: ""
  host: poeticmetric.com
  restApi:
    ingress:
      annotations: {} # @schema additionalProperties: true
    replicas: 1
    resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  scheduler:
    resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  smtp:
    fromAddress: poeticmetric@poeticmetric.com
    host: ""
    password: ""
    port: 587
    user: ""
  stripe: {} # @schema additionalProperties: true
  unverifiedOrganizationDeletionDays: 7
  workers:
  - concurrency: 1
    name: ""
    queues: [ ]
    replicas: 1
rabbitmq:
  image:
    repository: rabbitmq
    tag: 3-management-alpine
  ingress:
    annotations: {} # @schema additionalProperties: true
    host: ""
  password: ""
  persistence:
    enabled: true
  serviceMonitor:
    enabled: true
  user: poeticmetric
valkey:
  image:
    pullPolicy: IfNotPresent
    repository: valkey/valkey
    tag: 8-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.2/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
