clickhouse:
  image:
    pullPolicy: IfNotPresent
    repository: clickhouse/clickhouse-server
    tag: 24-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
  resources: {}
  user: poeticmetric
ghcrAuth: ""
mailpit:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: axllent/mailpit
    tag: latest
  ingress:
    annotations: {}
    host: ""
pgbouncer:
  config: {}
  image:
    pullPolicy: IfNotPresent
    repository: bitnami/pgbouncer
    tag: "1"
  replicas: 1
  resources: {}
postgres:
  image:
    pullPolicy: IfNotPresent
    repository: postgres
    tag: 17-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
  resources: {}
  user: poeticmetric
poeticmetric:
  backend:
    image:
      pullPolicy: Always
      repository: ghcr.io/th0th/poeticmetric/backend
      tag: latest
  development:
    databaseDebug: false
    debug: false
    enabled: false
    hostBasePath: ""
  frontend:
    image:
      pullPolicy: Always
      repository: ghcr.io/th0th/poeticmetric/frontend
      tag: latest
    ingress:
      annotations: {}
    replicas: 1
    resources: {}
  host: poeticmetric.com
  restApi:
    ingress:
      annotations: {}
    replicas: 1
    resources: {}
  smtp:
    fromAddress: poeticmetric@poeticmetric.com
    host: ""
    password: ""
    port: 587
    user: ""
redis:
  image:
    pullPolicy: IfNotPresent
    repository: redis
    tag: 6.2-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
  resources: {}
