clickhouse:
  image:
    pullPolicy: IfNotPresent
    repository: clickhouse/clickhouse-server
    tag: 25.2
  password: ""
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    volumeName: ""
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  user: poeticmetric
gateway:
  parentRefs: []
mailpit:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: axllent/mailpit
    tag: latest
pgbouncer:
  config: {} # @schema additionalProperties: true
  image:
    pullPolicy: IfNotPresent
    repository: th0th/pgbouncer
    tag: "1"
  replicas: 1
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
poeticmetric:
  backend:
    image:
      pullPolicy: Always
      repository: code.unius.sh/unius/poeticmetric-backend
      tag: latest
  config: # @schema additionalProperties: true
    defaultPlanName: ""
    development:
      databaseDebug: false
      debug: false
      enabled: false
      hostBasePath: ""
    extra: {} # @schema additionalProperties: true
    google:
      clientID: ""
      clientSecret: ""
    host: poeticmetric.com
    isHosted: true
    registryAuth:
      host: ""
      password: ""
      user: ""
    restApi:
      basePath: /api
      replicas: 1
      resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
    scheduler:
      resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
    smtp:
      fromAddress: poeticmetric@poeticmetric.com
      host: ""
      password: ""
      port: 587
      user: ""
    stripe:
      metaEnvironment: ""
      publishableKey: ""
      secretKey: ""
      webhookSigningSecret: ""
    unverifiedOrganizationDeletionDays: 7
    workers:
      - concurrency: 1
        name: ""
        queues: []
        replicas: 1
        resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  frontend:
    allowRobots: true
    image:
      pullPolicy: Always
      repository: code.unius.sh/unius/poeticmetric-frontend
      tag: latest
    replicas: 1
    resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
    tagsEnvironment: ""
postHog:
  apiKey: ""
  assetsHostname: ""
  enabled: false
  hostname: ""
postgres:
  backupCronJob:
    destination:
      kind: ""
      path: ""
    enabled: false
    extraEnvFrom: [] # @schema itemRef: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.EnvFromSource ; skipProperties: true
    resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  image:
    pullPolicy: IfNotPresent
    repository: postgres
    tag: 17-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    volumeName: ""
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  user: poeticmetric
rabbitmq:
  image:
    repository: rabbitmq
    tag: 3-management-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    volumeName: ""
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
  serviceMonitor:
    enabled: true
  user: poeticmetric
valkey:
  image:
    pullPolicy: IfNotPresent
    repository: valkey/valkey
    tag: 8-alpine
  password: ""
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    volumeName: ""
  resources: {} # @schema $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements ; skipProperties: true
