{{ if .Values.postHog.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-posthog
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: {{ include "poeticmetric.fullname" . }}-posthog
  validation:
    hostname: eu.i.posthog.com
    wellKnownCACertificates: System
{{ end }}
