{{ if .Values.postHog.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-posthog
spec:
  endpoints:
    - fqdn:
        hostname: eu.i.posthog.com
        port: 443
{{ end }}
