apiVersion: v1
data:
  DATABASE: "poeticmetric"
  HOST: "{{ include "poeticmetric.fullname" . }}-pgbouncer"
  PORT: "6432"
  RAW_HOST: "{{ include "poeticmetric.fullname" . }}-postgres"
  RAW_PORT: "5432"
kind: ConfigMap
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-postgres
