apiVersion: v1
data:
  AUTH_TYPE: "scram-sha-256"
  {{ .Values.pgbouncer.config | toYaml | nindent 2 }}
kind: ConfigMap
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-pgbouncer
