apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "uniusAnalytics.labels" . | nindent 4 }}
  name: {{ include "uniusAnalytics.fullname" . }}-postgres
data:
  DATABASE: "unius_analytics"
  HOST: "{{ include "uniusAnalytics.fullname" . }}-pgbouncer"
  PORT: "6432"
  RAW_HOST: "{{ include "uniusAnalytics.fullname" . }}-postgres"
  RAW_PORT: "5432"
