apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poeticmetric.fullname" . }}-poeticmetric
data:
  BASE_PATH: {{ .Values.poeticmetric.ingress.path | quote }}
  COMMON_BASE_URL: {{ .Values.poeticmetric.commonBaseUrl | quote }}
  DEBUG: {{ .Values.poeticmetric.development.debug | quote }}
