apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-smtp
data:
  FROM_ADDRESS: {{ .Values.poeticmetric.config.smtp.fromAddress | quote }}
  HOST: {{ .Values.poeticmetric.config.smtp.host | quote }}
  PORT: {{ .Values.poeticmetric.config.smtp.port | quote }}
