apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-rabbitmq
data:
  HOST: "{{ include "poeticmetric.fullname" . }}-rabbitmq"
  PORT: "5672"
  VHOST: "webgazer"
