apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "uniusAnalytics.labels" . | nindent 4 }}
  name: {{ include "uniusAnalytics.fullname" . }}-pgbouncer
data:
  {{- toYaml .Values.pgbouncer.config | nindent 2 }}
