apiVersion: v1
data:
  HOST: "{{ include "poeticmetric.fullname" . }}-rabbitmq"
  PORT: "5672"
  VHOST: "poeticmetric"
kind: ConfigMap
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-rabbitmq
