apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poeticmetric.fullname" . }}-redis
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
data:
  HOST: "{{ include "poeticmetric.fullname" . }}-redis"
  PORT: "6379"
