apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uniusAnalytics.fullname" . }}-clickhouse
  labels:
    {{- include "uniusAnalytics.labels" . | nindent 4 }}
data:
  CONFIG: |
    <?xml version="1.0"?>
    <clickhouse>
      <asynchronous_metric_log remove="1" />
      <crash_log remove="1" />
      <metric_log remove="1" />
      <opentelemetry_span_log remove="1" />
      <part_log remove="1" />
      <postgresql_port>9005</postgresql_port>
      <processors_profile_log remove="1" />
      <query_log remove="1" />
      <query_thread_log remove="1" />
      <query_views_log remove="1" />
      <session_log remove="1" />
      <text_log remove="1" />
      <trace_log remove="1" />
      <zookeeper_log remove="1" />
    </clickhouse>
  DATABASE: "unius_analytics"
  HOST: "{{ include "uniusAnalytics.fullname" . }}-clickhouse"
  PORT: "9000"
