apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poeticmetric.fullname" . }}-pgbouncer
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.pgBouncer.config | nindent 2 }}
