apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uniusAnalytics.fullname" . }}-unius-analytics
data:
  DATABASE_DEBUG: {{ .Values.uniusAnalytics.development.databaseDebug | quote }}
  DEBUG: {{ .Values.uniusAnalytics.development.debug | quote }}
  BASE_PATH: {{ .Values.uniusAnalytics.basePath | quote }}
