{{ if and .Values.poeticmetric.config.development.enabled .Values.poeticmetric.config.stripe.secretKey }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-stripe-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: stripe-webhook
      {{ include "poeticmetric.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: stripe-webhook
        {{ include "poeticmetric.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - "stripe"
            - "listen"
            - "--forward-to"
            - "poeticmetric-rest-api/organization/stripe-webhook"
            - "--events"
            - "customer.subscription.created,customer.subscription.deleted,customer.subscription.updated"
            - "--latest"
          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: {{ include "poeticmetric.fullname" . }}-stripe
          image: stripe/stripe-cli:v1.27.0
          imagePullPolicy: IfNotPresent
          name: stripe-webhook
{{ end }}
