apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ if .Values.poeticmetric.restApi.ingress.annotations }}
    {{ toYaml .Values.poeticmetric.restApi.ingress.annotations | nindent 4 }}
    {{ end }}
  name: {{ include "poeticmetric.fullname" . }}-rest-api
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.poeticmetric.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "poeticmetric.fullname" . }}-rest-api
            port:
              number: 80
        path: /api/
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.poeticmetric.host }}
    secretName: {{ include "poeticmetric.fullname" . }}-rest-api-tls
