apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
      add_header X-Content-Type-Options "nosniff";
      add_header X-Frame-Options "sameorigin";

      set $cache_control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";

      if ($request_uri ~* \.(ttf)) {
      set $cache_control "public, max-age=31536000";
      }

      if ($request_uri ~* \.(gif|jpe?g|png)) {
      set $cache_control "public, max-age=2592000";
      }

      if ($request_uri ~* \.(css|js)) {
      set $cache_control "public, max-age=600";
      }

      # Apply the cache control header with the appropriate value
      add_header Cache-Control $cache_control;
    {{ toYaml .Values.uniusAnalytics.frontend.ingress.annotations | nindent 4 }}
  name: {{ include "uniusAnalytics.fullname" . }}-frontend
  labels:
    {{ include "uniusAnalytics.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.uniusAnalytics.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "uniusAnalytics.fullname" . }}-frontend
            port:
              number: 80
        path: {{ .Values.uniusAnalytics.basePath }}/
        pathType: Prefix
      {{ if .Values.uniusAnalytics.development.enabled }}
      - backend:
          service:
            name: {{ include "uniusAnalytics.fullname" . }}-frontend
            port:
              number: 24678
        path: {{ .Values.uniusAnalytics.basePath }}/hmr
        pathType: Prefix
      {{ end }}
  tls:
  - hosts:
    - {{ .Values.uniusAnalytics.host }}
    secretName: {{ include "uniusAnalytics.fullname" . }}-frontend-tls
