apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ toYaml .Values.poeticmetric.config.restApi.ingress.annotations | nindent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ include "poeticmetric.fullname" . }}-rest-api
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.poeticmetric.config.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "poeticmetric.fullname" . }}-rest-api
            port:
              number: 80
        path: {{ .Values.poeticmetric.config.restApi.basePath }}/(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.poeticmetric.config.host }}
    secretName: {{ include "poeticmetric.fullname" . }}-rest-api-tls
