apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-smtp
stringData:
  PASSWORD: "{{ .Values.poeticmetric.config.smtp.password }}"
  USER: "{{ .Values.poeticmetric.config.smtp.user }}"
