{{ if .Values.poeticmetric.config.stripe }}
apiVersion: v1
data:
  PUBLISHABLE_KEY: {{ .Values.poeticmetric.config.stripe.publishableKey | b64enc }}
  SECRET_KEY: {{ .Values.poeticmetric.config.stripe.secretKey | b64enc }}
  WEBHOOK_SIGNING_SECRET: {{ .Values.poeticmetric.config.stripe.webhookSigningSecret | b64enc }}
kind: Secret
metadata:
  labels: {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-stripe
{{ end }}
