apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-smtp
data:
  PASSWORD: {{ .Values.poeticmetric.config.smtp.password | b64enc }}
  USER: {{ .Values.poeticmetric.config.smtp.user | b64enc }}
