{{ if and .Values.poeticmetric.config.google.clientID .Values.poeticmetric.config.google.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-google
stringData:
  CLIENT_ID: "{{ .Values.poeticmetric.config.google.clientID }}"
  CLIENT_SECRET: "{{ .Values.poeticmetric.config.google.clientSecret }}"
{{ end }}
