{{ if .Values.poeticmetric.config.stripe }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-stripe
stringData:
  PUBLISHABLE_KEY: "{{ .Values.poeticmetric.config.stripe.publishableKey }}"
  SECRET_KEY: "{{ .Values.poeticmetric.config.stripe.secretKey }}"
  WEBHOOK_SIGNING_SECRET: "{{ .Values.poeticmetric.config.stripe.webhookSigningSecret }}"
{{ end }}
