apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-smtp
data:
  PASSWORD: {{ .Values.poeticmetric.smtp.password }}
  USER: {{ .Values.poeticmetric.smtp.user }}
