apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-postgres
stringData:
  PASSWORD: "{{ .Values.postgres.password | required ".Values.postgres.password is required!" }}"
  USER: "{{ .Values.postgres.user | required ".Values.postgres.user is required!" }}"
