apiVersion: v1
data:
  PASSWORD: {{ required ".Values.rabbitmq.password is required" .Values.rabbitmq.password | b64enc }}
  USER: {{ required ".Values.rabbitmq.user is required" .Values.rabbitmq.user | b64enc }}
kind: Secret
metadata:
  labels: {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-rabbitmq
