{{ if .Values.ghcrAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io
stringData:
  .dockerconfigjson: "{\"auths\":{\"ghcr.io\":{\"auth\":\"{{ .Values.ghcrAuth | b64enc }}\"}}}"
type: kubernetes.io/dockerconfigjson
{{ end }}
