apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-clickhouse
stringData:
  PASSWORD: "{{ .Values.clickhouse.password | required ".Values.clickhouse.password is required!" }}"
  USER: "{{ .Values.clickhouse.user | required ".Values.clickhouse.user is required!" }}"
