apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-clickhouse
data:
  PASSWORD: {{ .Values.clickhouse.password | required ".Values.clickhouse.password is required!" | b64enc }}
  USER: {{ .Values.clickhouse.user | required ".Values.clickhouse.user is required!" | b64enc }}
