apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-rabbitmq
stringData:
  PASSWORD: "{{ required ".Values.rabbitmq.password is required" .Values.rabbitmq.password }}"
  USER: "{{ required ".Values.rabbitmq.user is required" .Values.rabbitmq.user }}"
