{{ if and .Values.poeticmetric.config.google.clientID .Values.poeticmetric.config.google.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-google
data:
  CLIENT_ID: {{ .Values.poeticmetric.config.google.clientID | b64enc }}
  CLIENT_SECRET: {{ .Values.poeticmetric.config.google.clientSecret | b64enc }}
{{ end }}
