apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-valkey
spec:
  ports:
    - name: valkey
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    statefulSet: valkey
    {{ include "poeticmetric.selectorLabels" . | nindent 4 }}
