apiVersion: v1
kind: Service
metadata:
  name: {{ include "poeticmetric.fullname" . }}-redis
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    statefulSet: redis
    {{- include "poeticmetric.selectorLabels" . | nindent 4 }}
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
