apiVersion: v1
kind: Service
metadata:
  name: {{ include "poeticmetric.fullname" . }}-postgres
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    statefulSet: postgres
    {{- include "poeticmetric.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
