apiVersion: v1
kind: Service
metadata:
  name: {{ include "poeticmetric.fullname" . }}-clickhouse
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    statefulSet: clickhouse
    {{- include "poeticmetric.selectorLabels" . | nindent 4 }}
  ports:
  - name: clickhouse-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
