apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "uniusAnalytics.labels" . | nindent 4 }}
  name: {{ include "uniusAnalytics.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    statefulSet: postgres
    {{- include "uniusAnalytics.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
