{{ if .Values.mailpit.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-mailpit
spec:
  ports:
  - name: smtp
    port: 1025
    protocol: TCP
    targetPort: 1025
  - name: http
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    statefulSet: mailpit
    {{ include "poeticmetric.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{ end }}
