apiVersion: v1
kind: Service
metadata:
  name: {{ include "poeticmetric.fullname" . }}-pgbouncer
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    deployment: pgbouncer
    {{- include "poeticmetric.selectorLabels" . | nindent 4 }}
  ports:
  - name: pgbouncer
    port: 6432
    protocol: TCP
    targetPort: 6432
