apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "uniusAnalytics.labels" . | nindent 4 }}
  name: {{ include "uniusAnalytics.fullname" . }}-rest-api
spec:
  type: ClusterIP
  selector:
    {{- include "uniusAnalytics.selectorLabels" . | nindent 4 }}
    deployment: rest-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
