apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-rabbitmq
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: metrics
    port: 15692
    protocol: TCP
    targetPort: 15692
  - name: rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    statefulSet: rabbitmq
    {{ include "poeticmetric.selectorLabels" . | nindent 4 }}
  type: ClusterIP
