apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "poeticmetric.fullname" . }}-clickhouse
  labels:
    {{- include "poeticmetric.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      statefulSet: clickhouse
      {{- include "poeticmetric.selectorLabels" . | nindent 6 }}
  serviceName: clickhouse-hl
  template:
    metadata:
      labels:
        statefulSet: clickhouse
        {{- include "poeticmetric.selectorLabels" . | nindent 8 }}
      name: clickhouse
    spec:
      containers:
      - env:
        - name: CLICKHOUSE_DB
          valueFrom:
            configMapKeyRef:
              key: DATABASE
              name: {{ include "poeticmetric.fullname" . }}-clickhouse
              optional: false
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: {{ include "poeticmetric.fullname" . }}-clickhouse
              optional: false
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              key: USER
              name: {{ include "poeticmetric.fullname" . }}-clickhouse
              optional: false
        image: {{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}
        name: clickhouse
        resources: {{- toYaml .Values.clickhouse.resources | nindent 10 }}
        volumeMounts:
        - name: configmap-clickhouse
          mountPath: /etc/clickhouse-server/config.d/custom_config.xml
          subPath: CONFIG
        {{- if .Values.clickhouse.persistence.enabled }}
        - mountPath: /var/lib/clickhouse/
          name: data
          subPath: clickhouse
        {{- end }}
      volumes:
      - configMap:
          name: {{ include "poeticmetric.fullname" . }}-clickhouse
        name: configmap-clickhouse
  {{- if .Values.clickhouse.persistence.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
  {{- end }}
