apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{ include "poeticmetric.labels" . | nindent 4 }}
  name: {{ include "poeticmetric.fullname" . }}-postgres
spec:
  {{ if .Values.postgres.persistence.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  {{ end }}
  replicas: 1
  selector:
    matchLabels:
      statefulSet: postgres
      {{ include "poeticmetric.selectorLabels" . | nindent 6 }}
  serviceName: postgres-hl
  template:
    metadata:
      labels:
        statefulSet: postgres
        {{ include "poeticmetric.selectorLabels" . | nindent 8 }}
      name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DATABASE
                  name: {{ include "poeticmetric.fullname" . }}-postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: {{ include "poeticmetric.fullname" . }}-postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: USER
                  name: {{ include "poeticmetric.fullname" . }}-postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          name: postgres
          resources:
            {{ toYaml .Values.postgres.resources | nindent 12 }}
        {{ if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: postgres
        {{ end }}
  {{ if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
        storageClassName: {{ .Values.postgres.persistence.storageClassName }}
        volumeMode: Filesystem
        volumeName: {{ .Release.Namespace}}-{{ include "poeticmetric.fullname" . }}-postgres
  {{ end }}
