uniusAnalytics:
  backend:
    image:
      pullPolicy: Never
      tag: development
  development:
    debug: true
    enabled: true
  frontend:
    image:
      pullPolicy: Never
      tag: development
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: self-signed
  host: dev.unius.sh
  restApi:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: self-signed
