clickhouse:
  password: poeticmetric
  user: poeticmetric
mailpit:
  enabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: self-signed
poeticmetric:
  backend:
    image:
      pullPolicy: Never
      tag: development
  development:
    debug: true
    enabled: true
  frontend:
    image:
      pullPolicy: Never
      tag: development
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: self-signed
    tagsEnvironment: development
  host: dev.poeticmetric.com
  restApi:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: self-signed
  smtp:
    fromAddress: poeticmetric@dev.poeticmetric.com
    host: poeticmetric-mailpit
    port: "1025"
postgres:
  password: poeticmetric
redis:
  password: poeticmetric
