clickhouse:
  persistence:
    enabled: false
  resources: {}
pgbouncer:
  config: {}
  resources: {}
postgres:
  persistence:
    enabled: false
  resources: {}
poeticmetric:
  backend:
    image:
      tag: staging
  frontend:
    image:
      tag: staging
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-poeticmetric
    resources: {}
    tagsEnvironment: staging
  host: staging.poeticmetric.com
  restApi:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-poeticmetric
    resources: {}
  smtp:
    fromAddress: poeticmetric@staging.poeticmetric.com
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
valkey:
  persistence:
    enabled: false
  resources: {}
