clickhouse:
  persistence:
    enabled: false
postgres:
  persistence:
    enabled: false
poeticmetric:
  backend:
    image:
      tag: staging
  defaultPlanName: "Hobbyist"
  frontend:
    image:
      tag: staging
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-poeticmetric
    tagsEnvironment: staging
  host: staging.poeticmetric.com
  restApi:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-poeticmetric
  smtp:
    fromAddress: poeticmetric@staging.poeticmetric.com
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
  unverifiedOrganizationDeletionDays: 7
rabbitmq:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-poeticmetric
  persistence:
    enabled: false
valkey:
  persistence:
    enabled: false
